import Foundation

/// One Board Session's decoded VESC motor config (MCCONF), native-owned.
///
/// Scoped by MCCONF signature rather than firmware version: the signature *is* the layout identity,
/// generated by VESC's own code generator from the parameter set, and two firmwares sharing a
/// signature share a layout exactly (ADR 0036). Values restored from the cache come back
/// `lastKnown` — displayable, and never a write base, because this config is read-only permanently.
///
/// Every value is a finite `Double`; a field the layout does not carry is absent rather than zero.
///
/// @parity /modules/vescape-core/android/src/main/java/expo/modules/vescapecore/config/MotorConfigValues.kt
struct MotorConfigValues {
  let boardId: String?
  /// MCCONF signature the values were decoded against — the cache scope.
  let signature: UInt32
  /// Firmware branch whose layout carries this signature, e.g. `release_6_05`.
  let firmware: String
  let capturedAtMs: Int64
  let freshness: BoardConfigFreshness
  /// Decoded fields keyed by firmware field id, e.g. `l_temp_fet_start`.
  let values: [String: Double]

  /// A finite number field, or nil when the layout does not carry it.
  func number(_ id: String) -> Double? {
    guard let value = values[id], value.isFinite else { return nil }
    return value
  }

  /// Demote to `lastKnown`. Called when the BLE link drops: the values stay worth showing, but the
  /// disconnected window is where another tool could have rewritten the controller, so they stop
  /// claiming to describe the live board.
  /// @parity /modules/vescape-core/android/src/main/java/expo/modules/vescapecore/config/MotorConfigValues.kt `demotedToLastKnown`
  func demotedToLastKnown() -> MotorConfigValues {
    guard freshness == .fresh else { return self }
    return MotorConfigValues(
      boardId: boardId,
      signature: signature,
      firmware: firmware,
      capturedAtMs: capturedAtMs,
      freshness: .lastKnown,
      values: values
    )
  }

  /// @parity /modules/vescape-core/android/src/main/java/expo/modules/vescapecore/config/MotorConfigValues.kt `toBridgeMap`
  func toBridgeMap() -> [String: Any?] {
    [
      "boardId": boardId,
      "signature": signature,
      "firmware": firmware,
      "capturedAtMs": capturedAtMs,
      "freshness": freshness.rawValue,
      "values": values,
    ]
  }

  func valuesJson() -> String {
    guard let data = try? JSONSerialization.data(withJSONObject: values) else { return "{}" }
    return String(data: data, encoding: .utf8) ?? "{}"
  }

  /// Rebuild a cached object. Always lastKnown.
  static func lastKnown(
    boardId: String?,
    signature: UInt32,
    firmware: String,
    capturedAtMs: Int64,
    valuesJson: String
  ) -> MotorConfigValues {
    MotorConfigValues(
      boardId: boardId,
      signature: signature,
      firmware: firmware,
      capturedAtMs: capturedAtMs,
      freshness: .lastKnown,
      values: decodeValuesJson(valuesJson)
    )
  }

  private static func decodeValuesJson(_ json: String) -> [String: Double] {
    guard
      let data = json.data(using: .utf8),
      let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
    else { return [:] }
    var values: [String: Double] = [:]
    for (id, raw) in parsed {
      if let number = raw as? NSNumber, number.doubleValue.isFinite { values[id] = number.doubleValue }
    }
    return values
  }
}
