package expo.modules.vescapecore.config

import org.json.JSONObject

/**
 * One Board Session's decoded VESC motor config (MCCONF), native-owned.
 *
 * Scoped by MCCONF signature rather than firmware version: the signature *is* the layout identity,
 * generated by VESC's own code generator from the parameter set, and two firmwares sharing a
 * signature share a layout exactly (ADR 0036). Values restored from the cache come back
 * [BoardConfigFreshness.LAST_KNOWN] — displayable, and never a write base, because this config is
 * read-only permanently.
 *
 * Every value is a finite `Double`; a field the layout does not carry is absent rather than zero.
 *
 * @parity /modules/vescape-core/ios/config/MotorConfigValues.swift
 */
internal data class MotorConfigValues(
  val boardId: String?,
  /** MCCONF signature the values were decoded against — the cache scope. */
  val signature: Long,
  /** Firmware branch whose layout carries this signature, e.g. `release_6_05`. */
  val firmware: String,
  val capturedAtMs: Long,
  val freshness: BoardConfigFreshness,
  /** Decoded fields keyed by firmware field id, e.g. `l_temp_fet_start`. */
  val values: Map<String, Double>,
) {
  /** A finite number field, or null when the layout does not carry it. */
  fun number(id: String): Double? = values[id]?.takeIf { it.isFinite() }

  /**
   * Demote to [BoardConfigFreshness.LAST_KNOWN]. Called when the BLE link drops: the values stay worth
   * showing, but the disconnected window is where another tool could have rewritten the controller,
   * so they stop claiming to describe the live board.
   * @parity /modules/vescape-core/ios/config/MotorConfigValues.swift `demotedToLastKnown`
   */
  fun demotedToLastKnown(): MotorConfigValues =
    if (freshness == BoardConfigFreshness.FRESH) copy(freshness = BoardConfigFreshness.LAST_KNOWN) else this

  /** @parity /modules/vescape-core/ios/config/MotorConfigValues.swift `toBridgeMap` */
  fun toBridgeMap(): Map<String, Any?> = mapOf(
    "boardId" to boardId,
    "signature" to signature,
    "firmware" to firmware,
    "capturedAtMs" to capturedAtMs,
    "freshness" to freshness.wire,
    "values" to values,
  )

  fun valuesJson(): String = JSONObject(values as Map<*, *>).toString()

  companion object {
    /** Rebuild a cached object. Always lastKnown. */
    fun lastKnown(
      boardId: String?,
      signature: Long,
      firmware: String,
      capturedAtMs: Long,
      valuesJson: String,
    ): MotorConfigValues = MotorConfigValues(
      boardId = boardId,
      signature = signature,
      firmware = firmware,
      capturedAtMs = capturedAtMs,
      freshness = BoardConfigFreshness.LAST_KNOWN,
      values = decodeValuesJson(valuesJson),
    )

    /** JSON integral numbers read back as `Int`/`Long`, so every number is normalized to `Double`. */
    private fun decodeValuesJson(json: String): Map<String, Double> {
      val parsed = try {
        JSONObject(json)
      } catch (_: Exception) {
        return emptyMap()
      }
      val values = mutableMapOf<String, Double>()
      for (id in parsed.keys()) {
        (parsed.opt(id) as? Number)?.toDouble()?.takeIf { it.isFinite() }?.let { values[id] = it }
      }
      return values
    }
  }
}
