import {
  AndroidConfig,
  withAndroidManifest,
  withAppBuildGradle,
  withAppDelegate,
  type ConfigPlugin,
} from 'expo/config-plugins'

/**
 * Starts the native Sentry SDK on both platforms before the JS bundle loads, so a crash during
 * native startup is captured instead of vanishing.
 *
 * Android: the SDK (including the NDK signal handlers) boots from the manifest-driven
 * ContentProvider — before `Application.onCreate`, native module static init, and long before JS.
 *
 * `@sentry/react-native` ships `io.sentry.auto-init=false` in its library
 * manifest because it expects `Sentry.init()` in JS to boot the native SDK.
 * That leaves a blind spot: a native crash during startup (BLE module, Mapbox,
 * any Kotlin init) kills the app before JS runs, so nothing is ever captured —
 * and in a crash loop, previously cached envelopes are never uploaded either.
 * Overriding auto-init to true (with `tools:replace`, since the library value
 * would otherwise win the manifest merge) closes that gap. The later JS
 * `Sentry.init()` simply re-initializes the native SDK with the JS options.
 *
 * Sentry is off in dev: `io.sentry.auto-init` and `io.sentry.environment` are gradle manifest
 * placeholders, so the single prebuild-generated manifest yields auto-init only in release
 * builds (debug → false/development, release → true/production). JS matches — `initSentry` is
 * disabled under `__DEV__`.
 *
 * iOS: sentry-cocoa has no manifest equivalent — it only starts from code — so `SentrySDK.start`
 * is injected as the first statement of `application(_:didFinishLaunchingWithOptions:)`, ahead of
 * `startReactNative` and therefore ahead of every native module and the bundle. `#if !DEBUG`
 * compiles it out of debug builds, mirroring the Android manifest placeholder.
 *
 * On both platforms the later JS `Sentry.init()` re-initializes the native SDK with the JS
 * options; the early start only exists to cover the window before JS runs.
 *
 * No-op when `EXPO_PUBLIC_SENTRY_DSN` is unset at prebuild time (local dev without a DSN).
 * Release builds cannot reach that path: `scripts/release/verifyProductionConfig.ts` fails the
 * workflow before prebuild when the DSN is missing, and `verifySentryNativeInit.ts` asserts the
 * merged release manifest / generated AppDelegate actually starts Sentry before the artifact is
 * uploaded.
 */
const GRADLE_PLACEHOLDERS = `
// @generated by plugins/withSentryNativeInit — per-build-type Sentry environment
// Debug builds keep Sentry off entirely — local crashes are noise in the production stream.
android.buildTypes.debug.manifestPlaceholders += [sentryAutoInit: "false", sentryEnvironment: "development"]
android.buildTypes.release.manifestPlaceholders += [sentryAutoInit: "true", sentryEnvironment: "production"]
`

const APP_DELEGATE_ANCHOR = 'let delegate = ReactNativeDelegate()'
// Trailing newline matters: without it this also matches `import ReactAppDependencyProvider`.
const IMPORT_ANCHOR = 'import React\n'
const SENTRY_START_MARKER = 'SentrySDK.start'

// Injected in place of the anchor line, which already carries its own indentation.
const sentryStartSwift = (dsn: string) => `// @generated by plugins/withSentryNativeInit
#if !DEBUG
    ${SENTRY_START_MARKER} { options in
      options.dsn = "${dsn}"
      options.environment = "production"
      options.sendDefaultPii = false
      options.tracesSampleRate = 0
      // Covers what an in-process handler structurally cannot: watchdog terminations and OOM
      // kills, where the process is killed outright and SentryCrash never runs. The OS collects
      // those itself and hands them over on a later launch.
      // @parity /src/config/sentry.ts \`initSentry\`
      options.enableMetricKit = true
    }
#endif`

const withSentryNativeInit: ConfigPlugin = (config) => {
  const dsn = process.env.EXPO_PUBLIC_SENTRY_DSN
  if (!dsn) return config

  config = withAndroidManifest(config, (cfg) => {
    cfg.modResults.manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools'
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults)
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(app, 'io.sentry.dsn', dsn)
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      app,
      'io.sentry.auto-init',
      '${sentryAutoInit}',
    )
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      app,
      'io.sentry.environment',
      '${sentryEnvironment}',
    )

    const autoInit = app['meta-data']?.find(
      (item) => item.$['android:name'] === 'io.sentry.auto-init',
    )
    if (autoInit) {
      ;(autoInit.$ as Record<string, string>)['tools:replace'] = 'android:value'
    }
    return cfg
  })

  config = withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes('sentryEnvironment')) {
      cfg.modResults.contents += GRADLE_PLACEHOLDERS
    }
    return cfg
  })

  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `withSentryNativeInit: expected a Swift AppDelegate, got "${cfg.modResults.language}"`,
      )
    }
    if (cfg.modResults.contents.includes(SENTRY_START_MARKER)) return cfg

    if (!cfg.modResults.contents.includes(APP_DELEGATE_ANCHOR)) {
      throw new Error(
        `withSentryNativeInit: AppDelegate anchor "${APP_DELEGATE_ANCHOR}" not found — the Expo template changed, native Sentry init would silently not run.`,
      )
    }

    cfg.modResults.contents = cfg.modResults.contents
      .replace(IMPORT_ANCHOR, `${IMPORT_ANCHOR}import Sentry\n`)
      .replace(APP_DELEGATE_ANCHOR, `${sentryStartSwift(dsn)}\n\n    ${APP_DELEGATE_ANCHOR}`)

    // The import is positional like the anchor, but its failure mode is a Swift compile error long
    // after prebuild, so it is worth its own check rather than the anchor's.
    if (!cfg.modResults.contents.includes('import Sentry')) {
      throw new Error(
        `withSentryNativeInit: could not add "import Sentry" — "${IMPORT_ANCHOR}" not found in the AppDelegate.`,
      )
    }
    return cfg
  })
}

export default withSentryNativeInit
