import { theme } from '@/constants/theme'

/** One Dark admin boundaries and every label drawn over the ground layers. */
export const ONE_DARK_OVERLAY_LAYERS = [
  // --- admin boundaries ---
  {
    id: 'admin-1-boundary',
    type: 'line',
    source: 'composite',
    'source-layer': 'admin',
    filter: ['==', ['get', 'admin_level'], 1],
    paint: {
      'line-color': '#53657b',
      'line-width': 1.2,
      'line-dasharray': [4, 3],
      'line-opacity': 0.5,
    },
  },
  {
    id: 'admin-0-boundary',
    type: 'line',
    source: 'composite',
    'source-layer': 'admin',
    filter: ['all', ['==', ['get', 'admin_level'], 0], ['!=', ['get', 'maritime'], 1]],
    paint: {
      'line-color': '#7890a8',
      'line-width': 1.5,
      'line-opacity': 0.6,
    },
  },

  // --- labels ---
  {
    id: 'water-label',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'natural_label',
    filter: ['==', ['get', 'class'], 'water'],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 8, 10, 14, 13],
    },
    paint: {
      'text-color': theme.palette.sky.color,
      'text-halo-color': theme.palette.sky.bg,
      'text-halo-width': 1,
    },
  },
  {
    id: 'road-label',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'road',
    minzoom: 13,
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Regular', 'Arial Unicode MS Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 13, 9, 18, 13],
      'symbol-placement': 'line',
      'text-max-angle': 30,
    },
    paint: {
      'text-color': '#8ba4bf',
      'text-halo-color': '#172033',
      'text-halo-width': 1.5,
    },
  },
  {
    id: 'poi-label',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'poi_label',
    minzoom: 6,
    filter: ['<=', ['get', 'filterrank'], ['+', ['step', ['zoom'], 0, 16, 1, 17, 2], 3]],
    layout: {
      'icon-image': [
        'coalesce',
        [
          'case',
          ['has', 'maki_beta'],
          ['coalesce', ['image', ['get', 'maki_beta']], ['image', ['get', 'maki']]],
          ['image', ['get', 'maki']],
        ],
        [
          'image',
          [
            'match',
            ['get', 'class'],
            'park_like',
            'park',
            'education',
            'school',
            'medical',
            'hospital',
            'parking',
            'parking',
            'place_of_worship',
            'place-of-worship',
            'sport_and_leisure',
            'pitch',
            '',
          ],
        ],
      ],
      'icon-size': ['interpolate', ['linear'], ['zoom'], 14, 0.75, 18, 1],
      'icon-allow-overlap': false,
      'icon-padding': 3,
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Regular', 'Arial Unicode MS Regular'],
      'text-size': 11,
      'text-offset': ['literal', [0, 1.15]],
      'text-anchor': 'top',
    },
    paint: {
      'icon-color': '#8ba4bf',
      'icon-halo-width': 0,
      'icon-opacity': 0.76,
      'text-color': '#7890a8',
      'text-halo-color': '#172033',
      'text-halo-width': 1,
    },
  },
  {
    id: 'transit-label',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'transit_stop_label',
    minzoom: 13,
    layout: {
      'icon-image': [
        'image',
        [
          'match',
          ['get', 'mode'],
          'bus',
          'bus',
          'tram',
          'rail-light',
          ['literal', ['rail', 'metro_rail']],
          'rail',
          'ferry',
          'ferry',
          'bus',
        ],
      ],
      'icon-size': ['interpolate', ['linear'], ['zoom'], 13, 0.75, 18, 1],
      'icon-allow-overlap': false,
      'icon-padding': 3,
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Regular', 'Arial Unicode MS Regular'],
      'text-size': 11,
      'text-offset': ['literal', [0, 1.15]],
      'text-anchor': 'top',
    },
    paint: {
      'icon-color': '#8ba4bf',
      'icon-halo-width': 0,
      'icon-opacity': 0.76,
      'text-color': '#7890a8',
      'text-halo-color': '#172033',
      'text-halo-width': 1,
    },
  },
  {
    id: 'place-label-region',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 3,
    maxzoom: 9,
    filter: [
      'any',
      ['==', ['get', 'class'], 'state'],
      ['==', ['get', 'class'], 'province'],
      ['==', ['get', 'type'], 'state'],
      ['==', ['get', 'type'], 'province'],
    ],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 3, 9, 7, 13, 9, 15],
      'text-transform': 'uppercase',
      'text-letter-spacing': 0.08,
      'text-padding': 16,
    },
    paint: {
      'text-color': '#718096',
      'text-halo-color': '#172033',
      'text-halo-width': 1.5,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 3, 0.5, 6, 0.72, 9, 0.4],
    },
  },
  {
    id: 'place-label-subdivision',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 8,
    filter: [
      'any',
      ['==', ['get', 'class'], 'settlement_subdivision'],
      ['==', ['get', 'type'], 'settlement_subdivision'],
      ['==', ['get', 'type'], 'suburb'],
      ['==', ['get', 'type'], 'neighbourhood'],
      ['==', ['get', 'type'], 'neighborhood'],
      ['==', ['get', 'type'], 'quarter'],
    ],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Regular', 'Arial Unicode MS Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 8, 8, 12, 11, 15, 13],
      'text-padding': 18,
    },
    paint: {
      'text-color': '#6f8197',
      'text-halo-color': '#172033',
      'text-halo-width': 1.2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0.4, 12, 0.68, 15, 0.78],
    },
  },
  {
    id: 'place-label-town',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 8,
    filter: ['==', ['get', 'type'], 'town'],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 8, 9, 14, 14],
      'text-padding': 8,
    },
    paint: {
      'text-color': '#8fa1b5',
      'text-halo-color': '#172033',
      'text-halo-width': 1.5,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0.55, 10, 0.78, 14, 0.9],
    },
  },
  {
    id: 'place-label-village',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 11,
    filter: ['==', ['get', 'type'], 'village'],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Regular', 'Arial Unicode MS Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 11, 8, 15, 11],
      'text-padding': 14,
    },
    paint: {
      'text-color': '#73869b',
      'text-halo-color': '#172033',
      'text-halo-width': 1.2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 11, 0.35, 13, 0.55, 15, 0.72],
    },
  },
  {
    id: 'place-label-hamlet',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 13,
    filter: ['==', ['get', 'type'], 'hamlet'],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Regular', 'Arial Unicode MS Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 13, 7.5, 16, 10],
      'text-padding': 18,
    },
    paint: {
      'text-color': '#64758a',
      'text-halo-color': '#172033',
      'text-halo-width': 1,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.25, 15, 0.45, 16, 0.62],
    },
  },
  {
    id: 'place-label-city',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    filter: ['==', ['get', 'type'], 'city'],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Bold', 'Arial Unicode MS Bold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 4, 10, 10, 18, 14, 22],
    },
    paint: {
      'text-color': '#abb2bf',
      'text-halo-color': '#172033',
      'text-halo-width': 2,
    },
  },
  {
    id: 'place-label-country',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    filter: ['==', ['get', 'class'], 'country'],
    layout: {
      'text-field': ['get', 'name'],
      'text-font': ['DIN Pro Bold', 'Arial Unicode MS Bold'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 2, 10, 6, 16],
      'text-transform': 'uppercase',
      'text-letter-spacing': 0.1,
    },
    paint: {
      'text-color': '#8ba4bf',
      'text-halo-color': '#172033',
      'text-halo-width': 2,
    },
  },
]
