import { mock } from 'bun:test'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

interface NativeColor {
  resource_paths: string[]
}

const nativeColors = new Map<string, NativeColor>()

mock.module('react-native', () => ({
  Platform: { OS: 'android' },
  DynamicColorIOS: () => ({}),
  PlatformColor: (resource: string) => {
    const color = { resource_paths: [resource] }
    nativeColors.set(resource, color)
    return color
  },
}))

const { ALPHA_RESOURCE_SUFFIX, resolveAdaptiveColor } = await import('../src/constants/theme')

const ROOT = join(import.meta.dir, '..')
const CHECK = process.argv.includes('--check')
const RESOURCE_PREFIX = '@color/vescape_'

const baseColors = [...nativeColors.entries()]
  .filter(([resource]) => !resource.includes('_alpha_'))
  .map(([resource, color]) => ({
    name: resource.slice(RESOURCE_PREFIX.length),
    dark: resolveAdaptiveColor(color, 'dark') as string,
    light: resolveAdaptiveColor(color, 'light') as string,
  }))
  .sort((left, right) => left.name.localeCompare(right.name))

function androidColor(color: string): string {
  if (!/^#[0-9a-f]{6}$/i.test(color)) throw new Error(`Expected #rrggbb, received ${color}`)
  return color.toUpperCase()
}

function withAlpha(color: string, level: number): string {
  const alpha = Math.round(level * 255)
    .toString(16)
    .padStart(2, '0')
  return `#${alpha}${color.slice(1)}`.toUpperCase()
}

function render(appearance: 'light' | 'dark'): string {
  const base = baseColors.map(
    ({ name, ...colors }) =>
      `  <color name="vescape_${name}">${androidColor(colors[appearance])}</color>`,
  )
  const alpha = baseColors.flatMap(({ name, ...colors }) =>
    Object.entries(ALPHA_RESOURCE_SUFFIX).map(
      ([level, suffix]) =>
        `  <color name="vescape_${name}_alpha_${suffix}">${withAlpha(colors[appearance], Number(level))}</color>`,
    ),
  )

  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<resources>',
    '  <!-- Generated by scripts/generate-android-theme.ts. Do not edit. -->',
    ...base,
    '',
    ...alpha,
    '</resources>',
    '',
  ].join('\n')
}

for (const [qualifier, appearance] of [
  ['values', 'light'],
  ['values-night', 'dark'],
] as const) {
  const path = join(ROOT, 'modules/vescape-core/android/src/main/res', qualifier, 'colors.xml')
  const generated = render(appearance)

  if (CHECK) {
    if (readFileSync(path, 'utf8') !== generated) {
      throw new Error(`${path} is stale; run bun run theme:android`)
    }
  } else {
    writeFileSync(path, generated)
  }
}

console.log(CHECK ? 'Android theme resources are current' : 'Generated Android theme resources')
