/**
 * Port Phosphor icons into Android VectorDrawables for the Wear OS app.
 *
 * The wrist has no icon library: Compose on Wear draws `painterResource` drawables, and pulling in
 * a font or an SVG runtime for nine glyphs would cost more than the glyphs. Phosphor's source SVGs
 * are mechanical to convert — a 256x256 viewBox, no transforms, no gradients, and duotone is just a
 * second path at `opacity="0.2"` — so this emits the XML instead of hand-tracing paths.
 *
 * Add a name to ICONS and rerun; output is committed, since a Gradle codegen step for a file that
 * changes once a quarter is not worth the build complexity.
 *
 *   bun run icons:port
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** Phosphor icon names to port, in the `kebab-case` the asset package uses. */
const ICONS = [
  'sun',
  'moon-stars',
  'cloud-sun',
  'cloud-moon',
  'cloud',
  'cloud-fog',
  'cloud-rain',
  'cloud-snow',
  'cloud-lightning',
  'drop',
  'map-pin',
  'lightbulb',
  'headlights',
  'target',
]

const WEIGHT = 'duotone'
const ASSET_DIR = join(import.meta.dir, '../node_modules/@phosphor-icons/core/assets', WEIGHT)
const OUT_DIR = join(import.meta.dir, '../watch/wearos/src/main/res/drawable')

/** Phosphor's canvas. Emitted as a 24dp drawable so it lines up with Material icon sizing. */
const VIEWPORT = 256
const SIZE_DP = 24

interface SvgPath {
  d: string
  opacity: number
}

/**
 * Pull the `<path>` elements out of a Phosphor SVG. Deliberately a regex and not an XML parser:
 * these files are machine-generated with one shape per path, no nesting and no transforms, and a
 * parser dependency would outweigh the twelve lines it saves. Anything more exotic trips the
 * assertion below rather than silently emitting a wrong glyph.
 */
function parsePaths(svg: string, name: string): SvgPath[] {
  if (/<(g|use|circle|rect|polygon|linearGradient)\b/.test(svg)) {
    throw new Error(`${name}: unsupported SVG element — this converter only handles flat <path>s`)
  }
  const paths = [...svg.matchAll(/<path\b([^>]*)\/>/g)].map((match) => {
    const attrs = match[1] ?? ''
    const d = /\bd="([^"]+)"/.exec(attrs)?.[1]
    if (!d) throw new Error(`${name}: <path> without a d attribute`)
    return { d, opacity: Number(/\bopacity="([^"]+)"/.exec(attrs)?.[1] ?? '1') }
  })
  if (paths.length === 0) throw new Error(`${name}: no paths found`)
  return paths
}

/**
 * A VectorDrawable of the same shapes. Every path is filled white: Compose tints the whole drawable
 * at the call site, and an SrcIn tint keeps per-path alpha, which is exactly what makes the duotone
 * back layer still read as a back layer.
 */
function toVectorDrawable(paths: SvgPath[]): string {
  const body = paths
    .map((path) => {
      const alpha = path.opacity === 1 ? '' : `\n        android:fillAlpha="${path.opacity}"`
      return `    <path\n        android:fillColor="#FFFFFFFF"${alpha}\n        android:pathData="${path.d}" />`
    })
    .join('\n')
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/phosphor-to-vector.ts from @phosphor-icons/core. Do not edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${SIZE_DP}dp"
    android:height="${SIZE_DP}dp"
    android:viewportWidth="${VIEWPORT}"
    android:viewportHeight="${VIEWPORT}">
${body}
</vector>
`
}

mkdirSync(OUT_DIR, { recursive: true })
for (const name of ICONS) {
  const svg = readFileSync(join(ASSET_DIR, `${name}-${WEIGHT}.svg`), 'utf8')
  const out = join(OUT_DIR, `ic_ph_${name.replaceAll('-', '_')}.xml`)
  writeFileSync(out, toVectorDrawable(parsePaths(svg, name)))
  console.log(`ic_ph_${name.replaceAll('-', '_')}.xml`)
}
console.log(`${ICONS.length} icons -> ${OUT_DIR}`)
