import type { Href } from 'expo-router'

export const routes = {
  home: '/',
  profileStats: '/profile-stats',
  signIn: '/sign-in',
  account: '/account',
  settings: '/settings',
  settingsDev: '/settings/dev',
  settingsDebugRecordings: '/settings/debug-recordings' as Href,
  settingsComponents: '/settings/components',
  settingsComponentsTheme: '/settings/components/theme' as Href,
  settingsNavigationDiagnostic: '/settings/navigationDiagnostic',
  settingsOther: '/settings/other',
  tune: '/tune',
  tuneHistory: '/tune/history',
  addBoardScan: '/addBoard/scan',
  addBoard: '/addBoard',
  editBoard: '/editBoard/[boardId]',
  editBoardLink: '/editBoard/link',
  editBoardConfig: '/editBoard/config',
  controlSpeed: '/control/speed',
  controlBattery: '/control/battery',
  controlBatteryRaw: '/control/battery/raw' as Href,
  controlDuty: '/control/duty',
  controlMotorTemp: '/control/motor-temp',
  controlControllerTemp: '/control/controller-temp',
  controlMotorCurrent: '/control/motor-current',
  controlBatteryCurrent: '/control/battery-current',
  controlState: '/control/state',
  controlFootpad: '/control/footpad',
  controlImu: '/control/imu',
  settingsRawSettings: '/settings/raw-settings' as Href,
  settingsDiagnosticEvents: '/settings/eventLog' as Href,
  settingsPrivacyZones: '/settings/privacy-zones' as Href,
  settingsConnection: '/settings/connection' as Href,
  settingsDiagnostics: '/settings/diagnostics' as Href,
  settingsLiveTelemetry: '/settings/live-telemetry' as Href,
  settingsVisuals: '/settings/visuals' as Href,
  settingsMap: '/settings/map' as Href,
  settingsWatch: '/settings/watch' as Href,
  settingsHardware: '/settings/hardware' as Href,
  settingsHistory: '/settings/history' as Href,
  settingsGraphs: '/settings/graphs' as Href,
  settingsDatabase: '/settings/database' as Href,
  settingsAbout: '/settings/about' as Href,
  settingsReleaseNotes: '/settings/release-notes' as Href,
  devMapPlayground: '/dev/map-playground' as Href,
  historyCharts: '/history/charts' as Href,
} as const

export const stackScreens = {
  home: 'index',
  profileStats: 'profile-stats',
  signIn: 'sign-in',
  account: 'account',
  settings: 'settings',
  settingsDev: 'settings/dev',
  settingsDebugRecordings: 'settings/debug-recordings',
  settingsComponents: 'settings/components',
  settingsComponentsTheme: 'settings/components/theme',
  settingsNavigationDiagnostic: 'settings/navigationDiagnostic',
  settingsDiagnosticEvents: 'settings/eventLog',
  settingsOther: 'settings/other',
  tune: 'tune/index',
  tuneHistory: 'tune/history',
  addBoardScan: 'addBoard/scan',
  addBoard: 'addBoard/index',
  editBoard: 'editBoard/[boardId]',
  editBoardLink: 'editBoard/link',
  editBoardConfig: 'editBoard/config',
  controlBatteryRaw: 'control/battery/raw',
  settingsRawSettings: 'settings/raw-settings',
  settingsPrivacyZones: 'settings/privacy-zones',
  settingsConnection: 'settings/connection',
  settingsDiagnostics: 'settings/diagnostics',
  settingsLiveTelemetry: 'settings/live-telemetry',
  settingsVisuals: 'settings/visuals',
  settingsMap: 'settings/map',
  settingsWatch: 'settings/watch',
  settingsHardware: 'settings/hardware',
  settingsHistory: 'settings/history',
  settingsGraphs: 'settings/graphs',
  settingsDatabase: 'settings/database',
  settingsAbout: 'settings/about',
  settingsReleaseNotes: 'settings/release-notes',
  devMapPlayground: 'dev/map-playground',
  historyCharts: 'history/charts',
} as const
